services:
  homeassistant:
    container_name: homeassistant
    image: linuxserver/homeassistant:2026.1.3
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/MADRID
    volumes:
      - /docker-services/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
    mem_limit: 2g
    memswap_limit: 2g
  matter-server:
    image: ghcr.io/matter-js/python-matter-server:stable
    container_name: matter-server
    restart: unless-stopped
    network_mode: host
    security_opt:
      - apparmor:unconfined
    volumes:
      - /docker-services/matter-server/data:/data
      - /run/dbus:/run/dbus:ro
    deploy:
      resources:
        limits:
          memory: 256M
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    environment:
      - TZ=Europe/Madrid
    ports:
      - "64013:1880"
    restart: unless-stopped
    volumes:
      - /docker-services/node-red:/data
    deploy:
      resources:
        limits:
          memory: 128M
