services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /docker-services/portainer-data:/data
    ports:
      - 64003:9443
      - 64014:8000
    deploy:
      resources:
        limits:
          memory: 128M
